---
- name: Wait for SSH
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 120

- name: Apply ELK role
  hosts: all
  roles:
    - elk
